version: '3.4'

services:
  ui:
    image: docker-demo-ui
    build: angular-ui/.
    environment:
      NODE_ENV: production
    ports:
      - 80:80
    depends_on:
      - webapi
      - db

  api-gateway:
    image: apigw-base
    build: api-gateway/.
    # build: 
    #   context: .
    #   dockerfile: api-gateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 8080:80
    depends_on:
      - webapi
    volumes:
      - ./apiconfigs:/app/configuration

  webapi:
    image: docker-demo-user-api
    build: dotnetcore-webapi/.
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    # ports:
    #   - 8081:80
    depends_on:
      - db
  db:
    image: 'microsoft/mssql-server-linux'
    environment:
      SA_PASSWORD: 'Password1'
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Express'
    # ports:
    #   - 1433:1433